import {
  ACCESS_REQUEST_STATUS,
  ACCOUNT_PROVIDER,
  EVENT_KIND,
  MEMBERSHIP_STATUS,
  SESSION_STATUS,
  USER_STATUS,
} from "./shared/constants.js";

export function createSeedState() {
  return {
    users: [
      {
        id: 1,
        displayName: "Chris' Couch",
        email: "chris@bsrp.local",
        status: USER_STATUS.ACTIVE,
        createdAt: "2026-03-15T12:00:00.000Z",
      },
      {
        id: 2,
        displayName: "Jamie Lane",
        email: "lane@bsrp.local",
        status: USER_STATUS.ACTIVE,
        createdAt: "2026-03-15T12:00:00.000Z",
      },
    ],
    connectedAccounts: [
      {
        id: "connected_1",
        userId: 1,
        provider: ACCOUNT_PROVIDER.DISCORD,
        providerAccountId: "discord-chief",
        username: "chriscouch",
        guildMember: true,
        roles: ["guild_member", "community_owner", "leo_command"],
      },
      {
        id: "connected_2",
        userId: 2,
        provider: ACCOUNT_PROVIDER.DISCORD,
        providerAccountId: "discord-lane",
        username: "officerlane",
        guildMember: true,
        roles: ["guild_member", "leo_member"],
      },
    ],
    departments: [
      {
        id: "dept_1",
        slug: "community-leadership",
        name: "Community Leadership",
      },
      {
        id: "dept_2",
        slug: "sahp",
        name: "SAHP",
      },
    ],
    roles: [
      {
        id: "role_1",
        departmentId: "dept_1",
        slug: "owner",
        name: "Owner",
        sortOrder: 100,
        permissions: [
          "rbac.manage",
          "community.review_access",
          "community.manage_members",
          "operations.view_player",
          "integrations.manage_discord",
          "integrations.manage_fivem",
          "audit.view",
        ],
      },
      {
        id: "role_2",
        departmentId: "dept_2",
        slug: "superintendent",
        name: "Superintendent",
        sortOrder: 80,
        permissions: [
          "rbac.manage",
          "community.review_access",
          "operations.view_player",
          "integrations.manage_discord",
          "integrations.manage_fivem",
        ],
      },
      {
        id: "role_3",
        departmentId: "dept_2",
        slug: "trooper",
        name: "Trooper",
        sortOrder: 10,
        permissions: ["operations.view_player"],
      },
    ],
    memberships: [
      {
        id: "membership_1",
        userId: 1,
        departmentId: "dept_1",
        roleId: "role_1",
        status: MEMBERSHIP_STATUS.ACTIVE,
        assignedBy: "system",
      },
      {
        id: "membership_2",
        userId: 1,
        departmentId: "dept_2",
        roleId: "role_2",
        status: MEMBERSHIP_STATUS.ACTIVE,
        assignedBy: "system",
      },
      {
        id: "membership_3",
        userId: 2,
        departmentId: "dept_2",
        roleId: "role_3",
        status: MEMBERSHIP_STATUS.ACTIVE,
        assignedBy: 1,
      },
    ],
    permissionGrants: [],
    identityLinks: [
      {
        id: "identity_1",
        userId: 1,
        type: "fivem",
        license: "license:chief-harper",
        discordId: "discord-chief",
        linkedAt: "2026-03-15T12:00:00.000Z",
      },
      {
        id: "identity_2",
        userId: 2,
        type: "fivem",
        license: "license:lane",
        discordId: "discord-lane",
        linkedAt: "2026-03-15T12:00:00.000Z",
      },
    ],
    userGameAccess: [
      {
        id: "access_1",
        userId: 1,
        primaryLicense: "license:chief-harper",
        whitelistStatus: "approved",
        banStatus: "clear",
        notes: [],
      },
      {
        id: "access_2",
        userId: 2,
        primaryLicense: "license:lane",
        whitelistStatus: "approved",
        banStatus: "clear",
        notes: [],
      },
    ],
    serverConnections: [
      {
        id: "server_1",
        name: "BSRP Main",
        environment: "production",
        status: "online",
      },
    ],
    operationalEvents: [
      {
        id: "event_1",
        kind: EVENT_KIND.ADMIN_ACTION,
        serverId: "server_1",
        accessId: "access_2",
        actorUserId: 1,
        action: "warned",
        createdAt: "2026-03-15T12:15:00.000Z",
        metadata: { reason: "Scene disruption" },
      },
    ],
    auditEvents: [
      {
        id: "audit_1",
        action: "seed.initialized",
        actorUserId: "system",
        targetType: "platform",
        targetId: "seed",
        createdAt: "2026-03-15T12:00:00.000Z",
        metadata: {},
      },
    ],
    accessRequests: [
      {
        id: "request_1",
        userId: 2,
        departmentId: "dept_2",
        requestedRoleId: "role_2",
        status: ACCESS_REQUEST_STATUS.PENDING,
        submittedAt: "2026-03-15T12:30:00.000Z",
      },
    ],
    sessions: [
      {
        id: "session_1",
        userId: 1,
        status: SESSION_STATUS.ACTIVE,
        createdAt: "2026-03-15T12:00:00.000Z",
      },
    ],
    oauthStates: [],
    integrationMappings: [
      {
        id: "mapping_1",
        provider: ACCOUNT_PROVIDER.DISCORD,
        externalRoleId: "community_owner",
        departmentId: "dept_1",
        roleId: "role_1",
        direction: "inbound",
      },
      {
        id: "mapping_2",
        provider: ACCOUNT_PROVIDER.DISCORD,
        externalRoleId: "leo_command",
        departmentId: "dept_2",
        roleId: "role_2",
        direction: "inbound",
      },
      {
        id: "mapping_3",
        provider: ACCOUNT_PROVIDER.DISCORD,
        externalRoleId: "leo_member",
        departmentId: "dept_2",
        roleId: "role_3",
        direction: "inbound",
      },
    ],
    processedEventKeys: [],
  };
}

